version: "3.8"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app-banco

  nginx:
    container_name: nginx
    build: images/nginx
    volumes:
      - ./:/usr/share/nginx/html/
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    depends_on:
      - db

  php:
    container_name: php
    build: images/php
    volumes:
      - ./:/usr/share/nginx/html/
    command: php-fpm
    ports:
      - "9000:9000"
    depends_on:
      - db
      
  adminer:
    image: adminer
    ports:
      - 8080:8080
    
